binop_separator = "Back"
brace_style = "PreferSameLine"
control_brace_style = "AlwaysSameLine"
comment_width = 80
edition = "2021"
enum_discrim_align_threshold = 40
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Lower"
imports_indent = "Block"
imports_layout = "Vertical"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
wrap_comments = true